---
language: java
install: true
script: $TARGET
jdk:
- openjdk7
- oraclejdk7
- oraclejdk8

env:
  matrix:
    - TARGET='mvn test'

notifications:
  email:
    - michael@mosmann.de
    - m.joehren@gmail.com
    - chrbayer84@googlemail.com
